security:
  oauth2:
    client:
      clientId: 52107347264-c7t6nj8elgrj6oqb8t9iauh0k6l9cha6.apps.googleusercontent.com
      clientSecret: QBgrojx31HutoZAG-gI4_OgE
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false 
